In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import requests

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("umbertogriffo/googles-trained-word2vec-model-in-python")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\write\.cache\kagglehub\datasets\umbertogriffo\googles-trained-word2vec-model-in-python\versions\1


In [4]:
import os

# Check the contents of the downloaded dataset directory
files = os.listdir(path)
print("Files in the dataset directory:", files)

# Access a specific file (for example, if there's a .bin file)
model_path = os.path.join(path, 'GoogleNews-vectors-negative300.bin')
print("Model file path:", model_path)


Files in the dataset directory: ['GoogleNews-vectors-negative300.bin', 'GoogleNews-vectors-negative300.bin.gz']
Model file path: C:\Users\write\.cache\kagglehub\datasets\umbertogriffo\googles-trained-word2vec-model-in-python\versions\1\GoogleNews-vectors-negative300.bin


In [5]:
model_path

'C:\\Users\\write\\.cache\\kagglehub\\datasets\\umbertogriffo\\googles-trained-word2vec-model-in-python\\versions\\1\\GoogleNews-vectors-negative300.bin'

In [6]:
model = KeyedVectors.load_word2vec_format(model_path, binary=True)

In [7]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [8]:
model['man'].shape

(300,)

In [9]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [10]:
model.similarity('man', 'PHP')

-0.032995153

In [11]:
model.doesnt_match(['php', 'java', 'cat'])

'cat'

In [12]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

# Converting Whole sentence into vectors

In [13]:
import numpy as np
import pandas as pd

In [14]:
temp_df = pd.read_csv('IMDB Dataset.csv')

In [15]:
df = temp_df.iloc[:10000]

In [16]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
df.drop_duplicates(inplace=True)

C:\Users\write\AppData\Local\Temp\ipykernel_19192\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [18]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [19]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\write\AppData\Local\Temp\ipykernel_19192\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [20]:
df['review'].head()

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. The filming tec...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: object

In [21]:
import gensim

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [22]:
story = []

for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [23]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
)

In [24]:
model.build_vocab(story)

In [25]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(8324866, 10950890)

In [26]:
len(model.wv.index_to_key)

31846

In [27]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    if len(doc) == 0:
        return np.zeros(model.vector_size)
    return np.mean(model.wv[doc], axis=0)

In [28]:
document_vector(df['review'].values[0])

array([-1.08555675e-01, -7.79920444e-02, -9.11573246e-02, -3.54876429e-01,
        4.30559486e-01, -5.07258236e-01,  6.78339243e-01,  5.26415706e-01,
        7.47905001e-02, -9.76191983e-02, -9.90083814e-02, -8.55144322e-01,
       -2.74972349e-01, -2.39641368e-01,  3.75409424e-01, -2.31957763e-01,
        1.67549010e-02,  9.07321349e-02, -2.98833579e-01,  8.53560492e-02,
       -4.43892293e-02, -2.96312049e-02, -5.83798110e-01, -3.46145183e-01,
       -1.91442937e-01, -2.57377177e-01,  1.59051940e-01, -1.18242335e-02,
       -2.61658460e-01, -1.37202024e-01, -1.86729431e-02,  5.08697294e-02,
       -2.04290241e-01, -2.60827988e-01, -5.01636922e-01,  5.30682147e-01,
        4.52123553e-01, -4.60043401e-02, -2.45022982e-01, -5.62171161e-01,
       -1.87313575e-02, -3.29153687e-01,  6.58597410e-01, -3.26405734e-01,
        2.45915234e-01,  1.74259469e-01,  5.26719168e-02, -1.75912678e-02,
        1.32976800e-01,  8.56541544e-02, -2.97591716e-01, -3.92929345e-01,
        3.80993366e-01,  

In [29]:
from tqdm import tqdm

In [30]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [06:13<00:00, 26.76it/s]


In [31]:
# using CPU cores for faster execution of iteration
from joblib import delayed, Parallel

In [32]:
X = []
X.extend(Parallel(n_jobs=-1)(delayed(document_vector)(doc) for doc in tqdm(df['review'].values)))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [02:18<00:00, 71.89it/s]


In [33]:
X = np.array(X)

In [34]:
X.shape

(9983, 100)

In [36]:
X[0]

array([-1.08555675e-01, -7.79920444e-02, -9.11573246e-02, -3.54876429e-01,
        4.30559486e-01, -5.07258236e-01,  6.78339243e-01,  5.26415706e-01,
        7.47905001e-02, -9.76191983e-02, -9.90083814e-02, -8.55144322e-01,
       -2.74972349e-01, -2.39641368e-01,  3.75409424e-01, -2.31957763e-01,
        1.67549010e-02,  9.07321349e-02, -2.98833579e-01,  8.53560492e-02,
       -4.43892293e-02, -2.96312049e-02, -5.83798110e-01, -3.46145183e-01,
       -1.91442937e-01, -2.57377177e-01,  1.59051940e-01, -1.18242335e-02,
       -2.61658460e-01, -1.37202024e-01, -1.86729431e-02,  5.08697294e-02,
       -2.04290241e-01, -2.60827988e-01, -5.01636922e-01,  5.30682147e-01,
        4.52123553e-01, -4.60043401e-02, -2.45022982e-01, -5.62171161e-01,
       -1.87313575e-02, -3.29153687e-01,  6.58597410e-01, -3.26405734e-01,
        2.45915234e-01,  1.74259469e-01,  5.26719168e-02, -1.75912678e-02,
        1.32976800e-01,  8.56541544e-02, -2.97591716e-01, -3.92929345e-01,
        3.80993366e-01,  

In [39]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [40]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=-1, verbose=2)

In [54]:
rf.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.


building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
b

[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:    0.2s


building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100building tree 83 of 100
building tree 84 of 100
building tree 85 

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    1.1s finished


RandomForestClassifier(n_jobs=-1, verbose=2)

In [55]:
y_pred = rf.predict(X_test)

[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 100 out of 100 | elapsed:    0.0s finished


In [57]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.7431146720080121